/**
 * @fileoverview Renders `VERIFICATION_REPORT.md`.
 *
 * The report is produced for every run (and written to the output directory when
 * verification ultimately fails) so a human has a single, self-contained
 * artifact describing what was checked, what passed, what failed, and what was
 * attempted to repair it.
 */
import type { StageName } from "./repair.js";

/** Result of one stage within a single verification pass. */
export interface StageOutcome {
  readonly stage: StageName;
  readonly ok: boolean;
  /** One-line human summary. */
  readonly detail: string;
  /** Full captured output (diagnostics, stderr) — included in the report. */
  readonly log: string;
  readonly durationMs: number;
}

/** A repair attempt recorded for the report. */
export interface RepairRecord {
  readonly iteration: number;
  readonly stage: StageName;
  readonly file: string;
  readonly applied: boolean;
  /** Why a repair could not be produced/applied, when relevant. */
  readonly note?: string;
}

/** Everything needed to render the report. */
export interface ReportInput {
  readonly ok: boolean;
  readonly serverName: string;
  readonly iterations: number;
  readonly maxRepairs: number;
  readonly repairs: readonly RepairRecord[];
  /** Stage outcomes from the final pass. */
  readonly stages: readonly StageOutcome[];
  readonly generatedAt: string;
}

const STAGE_TITLES: Record<StageName, string> = {
  install: "Install dependencies",
  build: "Type-check / build",
  boot: "Boot + tools/list",
  smoke: "Smoke-call tools",
};

function mark(ok: boolean): string {
  return ok ? "✅ pass" : "❌ fail";
}

/** Fenced block, trimmed and bounded so the report stays readable. */
function logBlock(log: string): string {
  const trimmed = log.trim();
  if (!trimmed) return "_(no output)_";
  const bounded =
    trimmed.length > 4000 ? `${trimmed.slice(-4000)}\n[...truncated...]` : trimmed;
  return ["```", bounded, "```"].join("\n");
}

/** Render the full `VERIFICATION_REPORT.md` body. */
export function renderReport(input: ReportInput): string {
  const lines: string[] = [];
  lines.push("# Verification report");
  lines.push("");
  lines.push(
    `**Server:** \`${input.serverName}\`  `,
    `**Result:** ${input.ok ? "✅ PASSED" : "❌ FAILED"}  `,
    `**Passes run:** ${input.iterations} (repair cap: ${input.maxRepairs})  `,
    `**Generated:** ${input.generatedAt}`,
  );
  lines.push("");
  lines.push(
    input.ok
      ? "The generated server installed, built, booted under a real MCP client, and answered a smoke call for every tool against a mocked upstream."
      : "Verification did not pass. The failing stage and its output are below; review before deploying.",
  );

  lines.push("", "## Stages (final pass)", "");
  lines.push("| Stage | Result | Detail |");
  lines.push("| ----- | ------ | ------ |");
  for (const stage of input.stages) {
    const detail = stage.detail.replace(/\|/g, "\\|").replace(/\n/g, " ");
    lines.push(
      `| ${STAGE_TITLES[stage.stage]} | ${mark(stage.ok)} | ${detail} (${stage.durationMs}ms) |`,
    );
  }

  if (input.repairs.length > 0) {
    lines.push("", "## Repairs attempted", "");
    for (const repair of input.repairs) {
      const status = repair.applied
        ? "patch applied"
        : `not applied${repair.note ? ` — ${repair.note}` : ""}`;
      lines.push(
        `- Pass ${repair.iteration}: \`${repair.file}\` (${repair.stage}) — ${status}.`,
      );
    }
  }

  const failed = input.stages.filter((s) => !s.ok);
  if (failed.length > 0) {
    lines.push("", "## Failure details", "");
    for (const stage of failed) {
      lines.push(`### ${STAGE_TITLES[stage.stage]}`, "");
      lines.push(stage.detail, "");
      lines.push(logBlock(stage.log), "");
    }
  }

  lines.push(
    "",
    "---",
    "_Generated by mcpgen's verification & self-repair loop._",
  );
  return `${lines.join("\n")}\n`;
}
