/**
 * @fileoverview The verification toolchain — the I/O boundary of the loop.
 *
 * Everything that touches the real world during verification (installing
 * dependencies, building with `tsc`, booting the server and driving it with a
 * real MCP client) goes through the {@link Toolchain} interface, mirroring how
 * the rest of `core` hides the model behind {@link LlmClient}. The default
 * {@link NodeToolchain} shells out to npm/tsc/node; tests inject a fake that
 * simulates outcomes, so the loop logic is exercised without network or builds.
 *
 * The boot + smoke stages run inside a tiny driver script ({@link DRIVER_SOURCE})
 * written into the project under test, so the MCP *client* is the SDK the
 * generated project itself installed — no MCP SDK dependency leaks into `core`.
 */
import { spawn } from "node:child_process";
import { openSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/** Outcome of dependency installation. */
export interface InstallOutcome {
  readonly ok: boolean;
  /** Combined stdout+stderr (for logs / repair context). */
  readonly output: string;
}

/** Outcome of the TypeScript build. */
export interface BuildOutcome {
  readonly ok: boolean;
  readonly output: string;
}

/** A single tool to invoke during the smoke stage. */
export interface DriverCall {
  readonly tool: string;
  readonly args: Record<string, unknown>;
}

/** Everything the driver needs to boot and exercise the server. */
export interface DriverSpec {
  /** Server entry relative to the project dir, e.g. `dist/server.js`. */
  readonly serverEntry: string;
  /** Extra env for the server process (e.g. `MCPGEN_API_BASE_URL`). */
  readonly env: Record<string, string>;
  /** Smoke calls to make after `tools/list`. */
  readonly calls: readonly DriverCall[];
}

/** Per-tool smoke-call result. */
export interface ToolCallResult {
  readonly tool: string;
  readonly ok: boolean;
  readonly isError: boolean;
  readonly message?: string;
}

/** Outcome of booting + smoke-testing the server. */
export interface DriverOutcome {
  /** Whether `initialize` + `tools/list` succeeded. */
  readonly bootOk: boolean;
  /** Tool names the server advertised. */
  readonly advertisedTools: readonly string[];
  /** Per-call smoke results (empty if boot failed). */
  readonly toolResults: readonly ToolCallResult[];
  /** Driver + server stderr (for logs / repair context). */
  readonly output: string;
}

/** The verification I/O boundary. */
export interface Toolchain {
  /** Install the project's dependencies in `dir`. */
  install(dir: string): Promise<InstallOutcome>;
  /** Type-check / build the project in `dir`. */
  build(dir: string): Promise<BuildOutcome>;
  /** Boot the built server and run the smoke calls. */
  runDriver(dir: string, spec: DriverSpec): Promise<DriverOutcome>;
}

/** Run a command, capturing combined output; resolves with the exit code. */
function run(
  command: string,
  args: string[],
  options: { cwd: string; timeoutMs: number; env?: NodeJS.ProcessEnv },
): Promise<{ code: number; output: string }> {
  return new Promise((resolve) => {
    const child = spawn(command, args, {
      cwd: options.cwd,
      env: options.env ?? process.env,
      stdio: ["ignore", "pipe", "pipe"],
    });
    let output = "";
    const collect = (chunk: Buffer): void => {
      output += chunk.toString();
    };
    child.stdout.on("data", collect);
    child.stderr.on("data", collect);

    const timer = setTimeout(() => {
      output += `\n[mcpgen] command timed out after ${options.timeoutMs}ms\n`;
      child.kill("SIGKILL");
    }, options.timeoutMs);

    child.on("error", (err) => {
      clearTimeout(timer);
      resolve({ code: 1, output: `${output}\n${err.message}` });
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve({ code: code ?? 1, output });
    });
  });
}

/** The MCP client driver, written into the project under test and run there. */
export const DRIVER_SOURCE = `// Generated by mcpgen verification — safe to delete.
import { readFileSync, writeFileSync } from "node:fs";
import { openSync } from "node:fs";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";

const [, , specPath, outPath, stderrPath] = process.argv;
const spec = JSON.parse(readFileSync(specPath, "utf8"));
const result = { bootOk: false, advertisedTools: [], toolResults: [], output: "" };

async function main() {
  const errFd = openSync(stderrPath, "w");
  const transport = new StdioClientTransport({
    command: process.execPath,
    args: [spec.serverEntry],
    cwd: process.cwd(),
    env: { ...process.env, ...spec.env },
    stderr: errFd,
  });
  const client = new Client({ name: "mcpgen-verify", version: "0.0.0" });
  await client.connect(transport); // performs MCP initialize
  const listed = await client.listTools();
  result.bootOk = true;
  result.advertisedTools = listed.tools.map((t) => t.name);
  for (const call of spec.calls ?? []) {
    const r = { tool: call.tool, ok: false, isError: false };
    try {
      const res = await client.callTool({
        name: call.tool,
        arguments: call.args ?? {},
      });
      const contentOk = Array.isArray(res.content) && res.content.length > 0;
      r.isError = res.isError === true;
      r.ok = contentOk && !res.isError;
      if (!contentOk) r.message = "result missing a content array";
      else if (res.isError)
        r.message =
          "handler returned isError=true: " +
          JSON.stringify(res.content).slice(0, 400);
    } catch (e) {
      r.message = String((e && e.message) || e);
    }
    result.toolResults.push(r);
  }
  await client.close();
}

main()
  .catch((e) => {
    result.output += String((e && e.stack) || (e && e.message) || e);
  })
  .finally(() => {
    try {
      result.output += "\\n" + readFileSync(stderrPath, "utf8");
    } catch {}
    writeFileSync(outPath, JSON.stringify(result));
    process.exit(0);
  });
`;

/** Options for {@link NodeToolchain}. */
export interface NodeToolchainOptions {
  /** Install command (default `npm install`). */
  readonly installCommand?: readonly string[];
  /** Timeout for install (default 180s). */
  readonly installTimeoutMs?: number;
  /** Timeout for build (default 120s). */
  readonly buildTimeoutMs?: number;
  /** Timeout for the driver (default 60s). */
  readonly driverTimeoutMs?: number;
}

/** The real toolchain: npm install, local `tsc`, and a node-driven MCP client. */
export class NodeToolchain implements Toolchain {
  constructor(private readonly options: NodeToolchainOptions = {}) {}

  async install(dir: string): Promise<InstallOutcome> {
    const [command, ...args] = this.options.installCommand ?? [
      "npm",
      "install",
      "--no-audit",
      "--no-fund",
      "--loglevel=error",
    ];
    const { code, output } = await run(command!, args, {
      cwd: dir,
      timeoutMs: this.options.installTimeoutMs ?? 180_000,
    });
    return { ok: code === 0, output };
  }

  async build(dir: string): Promise<BuildOutcome> {
    // Use the project's own locally-installed TypeScript.
    const tsc = join(
      dir,
      "node_modules",
      ".bin",
      process.platform === "win32" ? "tsc.cmd" : "tsc",
    );
    const { code, output } = await run(tsc, ["-p", "tsconfig.json"], {
      cwd: dir,
      timeoutMs: this.options.buildTimeoutMs ?? 120_000,
    });
    return { ok: code === 0, output };
  }

  async runDriver(dir: string, spec: DriverSpec): Promise<DriverOutcome> {
    const driverPath = join(dir, "__mcpgen_driver.mjs");
    const specPath = join(dir, "__mcpgen_spec.json");
    const outPath = join(dir, "__mcpgen_result.json");
    const stderrPath = join(dir, "__mcpgen_server.log");
    writeFileSync(driverPath, DRIVER_SOURCE);
    writeFileSync(specPath, JSON.stringify(spec));
    // Ensure the output file exists even if the driver dies hard.
    writeFileSync(outPath, JSON.stringify({ bootOk: false, advertisedTools: [], toolResults: [], output: "" }));
    openSync(stderrPath, "w");

    const { output } = await run(
      process.execPath,
      [driverPath, specPath, outPath, stderrPath],
      { cwd: dir, timeoutMs: this.options.driverTimeoutMs ?? 60_000 },
    );

    try {
      const parsed = JSON.parse(readFileSync(outPath, "utf8")) as DriverOutcome;
      return {
        bootOk: parsed.bootOk,
        advertisedTools: parsed.advertisedTools ?? [],
        toolResults: parsed.toolResults ?? [],
        output: `${output}\n${parsed.output ?? ""}`.trim(),
      };
    } catch (error) {
      return {
        bootOk: false,
        advertisedTools: [],
        toolResults: [],
        output: `${output}\n[mcpgen] could not read driver result: ${
          (error as Error).message
        }`,
      };
    }
  }
}
