/**
 * @fileoverview A deterministic, dependency-free runner used by tests and the
 * offline demo (`MCPGEN_FAKE=1`).
 *
 * It mirrors the real runner's *event shape* exactly — every generation and
 * verification stage — so the streaming UI and Playwright e2e exercise the full
 * happy path without an LLM, a network install, or a real toolchain. It even
 * re-parses the source via core so the tool list reflects real input.
 */
import type { Job, JobRunner } from "./jobs.js";
import type { JobEvent, JobSummary, StageKey } from "./protocol.js";
import { applyEdits, resolveSource } from "./parse.js";

const sleep = (ms: number): Promise<void> =>
  new Promise((r) => setTimeout(r, ms));

/** Per-stage simulated latency; kept tiny so e2e stays fast. */
const STEP_MS = Number(process.env.MCPGEN_FAKE_STEP_MS ?? 60);

async function stage(
  emit: (e: JobEvent) => void,
  group: "generate" | "verify",
  stageKey: StageKey,
  detail: string,
): Promise<void> {
  emit({ type: "stage", group, stage: stageKey, state: "start" });
  await sleep(STEP_MS);
  emit({
    type: "stage",
    group,
    stage: stageKey,
    state: "ok",
    detail,
    durationMs: STEP_MS,
  });
}

/** Render a believable, tiny generated project so download/viewer work. */
function fakeProject(
  serverName: string,
  toolNames: readonly string[],
): Map<string, string> {
  const files = new Map<string, string>();
  files.set(
    "package.json",
    JSON.stringify(
      { name: serverName, version: "0.1.0", type: "module" },
      null,
      2,
    ) + "\n",
  );
  files.set(
    "src/server.ts",
    `// ${serverName} — generated by mcpgen (demo)\nimport { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";\n\nexport const server = new McpServer({ name: ${JSON.stringify(serverName)}, version: "0.1.0" });\n`,
  );
  for (const name of toolNames) {
    files.set(
      `src/tools/${name}.ts`,
      `import { z } from "zod";\n\nexport const inputSchema = z.object({});\n\nexport async function ${name}(input: z.infer<typeof inputSchema>) {\n  // calls the upstream operation\n  return input;\n}\n`,
    );
  }
  files.set(
    "README.md",
    `# ${serverName}\n\nGenerated by **mcpgen** from your API. Run \`npm install && npm run build\`.\n`,
  );
  return files;
}

export const fakeRunner: JobRunner = async (job: Job, emit) => {
  const req = job.request;

  emit({ type: "phase", phase: "parsing" });
  await stage(emit, "generate", "parse", "reading source");
  const { source, kind } = await resolveSource({
    source: req.source,
    kind: req.kind,
  });
  const parsed = applyEdits(await source.parse(), req.tools);
  const toolNames = parsed.tools.map((t) => t.name);

  if (toolNames.length === 0) {
    throw new Error("No tools selected — enable at least one operation.");
  }

  const serverName = (parsed.metadata.title ?? "mcp-server")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .concat("-mcp");

  emit({ type: "phase", phase: "generating" });
  await stage(emit, "generate", "plan", `${kind} → ${serverName}`);
  await stage(emit, "generate", "synthesize", `${toolNames.length} tool(s)`);
  const files = fakeProject(serverName, toolNames);
  await stage(emit, "generate", "assemble", `${files.size} files`);

  let verification: JobSummary["verification"] = "skipped";
  if (req.verify) {
    emit({ type: "phase", phase: "verifying" });
    await stage(emit, "verify", "install", "dependencies installed");
    await stage(emit, "verify", "build", "tsc OK");
    await stage(
      emit,
      "verify",
      "boot",
      `tools/list → ${toolNames.length} tool(s)`,
    );
    await stage(emit, "verify", "smoke", "every tool returned a valid result");
    verification = { ok: true, passes: 1, repairs: 0 };
  }

  const summary: JobSummary = {
    serverName,
    toolCount: toolNames.length,
    transport: req.transport,
    usedFallback: false,
    note: "demo generation (MCPGEN_FAKE)",
    files: [...files.keys()].sort(),
    verification,
  };
  return { summary, files, serverName };
};
